import {JSDOM,VirtualConsole} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const products=JSON.parse(readFileSync('src/products.json'));
const goals=JSON.parse(readFileSync('src/goals.json'));
const routes=[...goals.map(g=>'goals/'+g.slug),'','shop','brands','why-ss','visit','search','bag',...products.map(p=>'products/'+p.slug)];
const script=readFileSync('dist/app.js','utf8');
function setup(route,search=''){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(readFileSync('dist/'+(route?route+'/':'')+'index.html','utf8'),{url:'https://test.invalid/'+(route?route+'/':'')+search,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
 const w=dom.window;w.matchMedia=q=>({matches:q.includes('prefers-reduced-motion'),media:q,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});w.IntersectionObserver=class{observe(){}disconnect(){}};w.ResizeObserver=class{observe(){}disconnect(){}};w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};w.eval(readFileSync('dist/catalog.js','utf8'));w.eval(readFileSync('dist/goals.js','utf8'));w.eval(script);return{dom,w,errors};
}
for(const route of routes){const {dom,w,errors}=setup(route);assert.equal(w.document.querySelectorAll('h1').length,1,route);assert.equal(w.document.querySelectorAll('nav a').length,14,route);assert.equal(errors.length,0,errors.join('\n'));dom.window.close()}
const shop=setup('shop','?brand=Dymatize');assert.equal(shop.w.document.querySelectorAll('#products .product-card').length,2);shop.w.document.querySelector('#clear-brand').click();assert.equal(shop.w.document.querySelectorAll('#products .product-card').length,products.length);shop.w.document.querySelector('[data-filter="Premium"]').click();assert.equal(shop.w.document.querySelectorAll('#products .product-card').length,4);const search=shop.w.document.querySelector('#search');search.value='PVL';search.dispatchEvent(new shop.w.Event('input',{bubbles:true}));assert.equal(shop.w.document.querySelectorAll('#products .product-card').length,1);shop.w.document.querySelector('[data-add]').click();assert.equal(shop.w.document.querySelector('#cart-count').textContent,'1');assert.equal(shop.errors.length,0);shop.dom.window.close();
const bag=setup('bag');bag.w.ssStore.add('mt',2);assert(bag.w.document.querySelector('#bag-page-items').textContent.includes('Nitro-Tech'));bag.w.document.querySelector('#bag-page-items [data-plus]').click();assert.equal(bag.w.document.querySelector('#cart-count').textContent,'3');const url=bag.w.document.querySelector('#bag-page-bottom .cart-send').href;assert(decodeURIComponent(url).includes('3 × MuscleTech Nitro-Tech'));bag.w.document.querySelector('#bag-page-items [data-remove]').click();assert(bag.w.document.querySelector('#bag-page-items').textContent.includes('Your bag is empty'));assert.equal(bag.errors.length,0);bag.dom.window.close();
const bundle=await build({entryPoints:['src/effects.jsx'],bundle:true,format:'iife',write:false,platform:'browser',define:{'process.env.NODE_ENV':'"production"'},jsx:'automatic'});
for(const route of ['', 'products/muscletech-nitro-tech']){const {dom,w,errors}=setup(route);w.eval(bundle.outputFiles[0].text);await new Promise(r=>setTimeout(r,80));if(!route){assert(w.document.querySelector('.campaign'));assert.equal(w.document.querySelectorAll('.campaign-pack').length,products.filter(p=>p.heroImage).length);w.document.querySelector('[aria-label="Next featured protein"]').click();await new Promise(r=>setTimeout(r,20));assert(w.document.querySelector('.campaign-card h2').textContent.includes('ISO100 Clear'));w.document.querySelector('.campaign-add').click();assert.equal(w.document.querySelector('#cart-count').textContent,'1')}else{assert(w.document.querySelector('.pdp-info'));w.document.querySelector('[aria-label="Increase quantity"]').click();await new Promise(r=>setTimeout(r,20));w.document.querySelector('.pdp-add').click();assert.equal(w.document.querySelector('#cart-count').textContent,'2');w.document.querySelector('#tab-1').click();await new Promise(r=>setTimeout(r,20));assert(w.document.querySelector('#product-panel').textContent.includes('label'))}assert.equal(errors.length,0,errors.join('\n'));dom.window.close()}
console.log('PASS: all routes; brand, premium and search filters; bag quantities/removal/enquiry; React carousel; product quantity/tabs; reduced-motion initialization.');

const menu=setup('shop','?category=Creatine');assert.equal(menu.w.document.querySelectorAll('#products .product-card').length,1);const toggle=menu.w.document.querySelector('#shop-toggle');toggle.click();assert.equal(toggle.getAttribute('aria-expanded'),'true');assert.equal(menu.w.document.querySelector('#shop-categories').hidden,false);menu.w.document.dispatchEvent(new menu.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(toggle.getAttribute('aria-expanded'),'false');menu.w.document.querySelector('#menu-toggle').click();assert(menu.w.document.querySelector('nav').classList.contains('open'));menu.w.document.querySelector('main').click();assert(!menu.w.document.querySelector('nav').classList.contains('open'));assert(menu.w.document.querySelector('.design-credit a').href==='https://aiavro.com/');menu.dom.window.close();console.log('PASS: category links, disclosure menu, Escape, mobile dismissal and footer credit.');

for(const g of goals){const page=setup('goals/'+g.slug);assert.equal(page.w.document.querySelectorAll('#products .product-card').length,g.ids.length);assert.equal(page.errors.length,0);page.dom.window.close()}
const review=setup('why-ss');review.w.eval(bundle.outputFiles[0].text);await new Promise(r=>setTimeout(r,80));assert(review.w.document.querySelector('.review-feature').textContent.includes('Divya Kotesh'));review.w.document.querySelector('[aria-label="Next customer review"]').click();await new Promise(r=>setTimeout(r,30));assert(review.w.document.querySelector('.review-feature').textContent.includes('Sujeet Ganji'));review.w.document.querySelector('[aria-label="Previous customer review"]').click();await new Promise(r=>setTimeout(r,30));assert(review.w.document.querySelector('.review-feature').textContent.includes('Divya Kotesh'));assert.equal(review.errors.length,0,review.errors.join('\n'));review.dom.window.close();console.log('PASS: five goal collections and customer review carousel.');
