import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import products from './products.json';
import Hero from './hero.jsx';
import Reviews from './reviews.jsx';
import {initMotion} from './scroll-motion.js';
function usePageMotion(){useEffect(()=>{const cleanup=initMotion();return cleanup},[])}

function useReducedMotion(){const [reduced,set]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)'),fn=()=>set(q.matches);q.addEventListener('change',fn);return()=>q.removeEventListener('change',fn)},[]);return reduced}
function Orbit({color,paused=false}){const host=useRef(null),api=useRef(null),reduced=useReducedMotion();useEffect(()=>{api.current?.setColor(color)},[color]);useEffect(()=>{if(api.current)api.current.paused=paused},[paused]);useEffect(()=>{if(reduced||matchMedia('(max-width: 760px)').matches||navigator.connection?.saveData)return;let dispose=()=>{},cancelled=false;import('./orbit.js').then(({createOrbit})=>{if(cancelled||!host.current)return;try{const result=createOrbit(host.current,color);api.current=result;result.paused=paused;dispose=()=>result.dispose()}catch{/* Product photography remains when WebGL is unavailable. */}}).catch(()=>{});return()=>{cancelled=true;dispose();api.current=null}},[reduced]);return <div className="orbit-canvas" ref={host} aria-hidden="true"/>}

function ProductCard({p}){return <article className="product-card" style={{'--card-tone':p.color,'--card-accent':p.accent}}><a className="product-image" href={'/products/'+p.slug+'/'}><span className="tag">{p.tag}</span><span className="pack-depth"><img src={p.image} alt={p.brand+' '+p.name} loading="lazy" width="260" height="300"/></span><span className="card-explore">Explore product ↗</span></a><div className="card-brand">{p.brand}</div><h3><a href={'/products/'+p.slug+'/'}>{p.name}</a></h3><div className="card-meta">{p.type}</div><div className="card-bottom"><span>Enquire for price</span><button className="add-btn" onClick={()=>window.ssStore.add(p.id)}>Add to bag +</button></div></article>}
function ProductPage({p}){usePageMotion();const [quantity,setQuantity]=useState(1),[tab,setTab]=useState('Overview'),[showSticky,setShowSticky]=useState(false),[added,setAdded]=useState(false);const gallery=useRef(null),buy=useRef(null),zoom=useRef(null),reduced=useReducedMotion();
useEffect(()=>{const io=new IntersectionObserver(([e])=>setShowSticky(!e.isIntersecting&&e.boundingClientRect.top<0),{threshold:0});io.observe(buy.current);return()=>io.disconnect()},[]);
const add=()=>{window.ssStore.add(p.id,quantity);setAdded(true)};const related=products.filter(x=>x.id!==p.id).sort((a,b)=>Number(b.category===p.category)-Number(a.category===p.category)).slice(0,3);
return <><div className="pdp-breadcrumb"><a href="/">Home</a><span>/</span><a href="/#shop">The supplement shelf</a><span>/</span><span>{p.name}</span></div>
<section className="pdp-hero" style={{'--pdp-color':p.color,'--pdp-accent':p.accent}}><div className="pdp-stage" ref={gallery}><div className="pdp-stage-inner"><div className="visual-top"><span>S&S SELECTS</span><span>{p.tag}</span></div><Orbit color={p.accent}/><div className="pdp-word" aria-hidden="true">{p.word}</div><button className="pdp-pack" onClick={()=>zoom.current.showModal()} aria-label={'Enlarge '+p.name+' packaging'}><img src={p.image} alt={p.brand+' '+p.name+' packaging'} width="600" height="600" fetchPriority="high"/></button><div className="pdp-image-bottom"><span>THE PRODUCT. UP CLOSE.</span><button onClick={()=>zoom.current.showModal()} aria-label="Enlarge product image">＋</button></div></div></div>
<div className="pdp-info"><div className="section-kicker">{p.brand} / {p.premium?'PREMIUM SELECTION':'THE SUPPLEMENT COLLECTION'}</div><h1>{p.name}</h1><p className="pdp-type">{p.type}</p><p className="pdp-description">{p.description}</p><div className="pdp-pricing"><strong>Good choices start with a conversation.</strong><p>Ask us for today’s price and availability.</p></div><div className="pdp-buy" ref={buy}><div className="pdp-qty"><span>Quantity</span><div><button onClick={()=>setQuantity(q=>Math.max(1,q-1))} disabled={quantity===1} aria-label="Decrease quantity">−</button><output aria-live="polite">{quantity}</output><button onClick={()=>setQuantity(q=>Math.min(99,q+1))} disabled={quantity===99} aria-label="Increase quantity">+</button></div></div><button className="button dark pdp-add" onClick={add}>{added?'Add another to bag':'Add to enquiry bag'}<span>↗</span></button>{added&&<button className="pdp-view-bag" onClick={()=>window.ssStore.openBag()}>View your bag →</button>}<small>Pack sizes, flavours and prices are confirmed by S&S. Your bag sends an enquiry; no payment is taken.</small></div><div className="pdp-service"><div><span>01</span><strong>Explore with confidence</strong><p>Compare the actual pack with our team.</p></div><div><span>02</span><strong>Your local nutrition store</strong><p>Banaswadi, Bengaluru. Call or visit us.</p></div></div><a className="text-link" href="tel:+917022825588">Need a hand choosing? +91 70228 25588 ↗</a></div></section>
<section className="pdp-story" style={{'--pdp-color':p.color,'--pdp-accent':p.accent}}><div className="section-kicker">A LITTLE MORE INTENT. EVERY DAY.</div><h2>{p.headline}</h2><div className="story-bottom"><span>{p.brand}</span><span>FOR EVERY REP. FOR EVERY VERSION OF YOU.</span><span>S&S</span></div></section>
<section className="pdp-details section"><div><div className="section-kicker">KNOW YOUR NEXT CHOICE</div><h2>THE DETAILS.<br/><span>NO GUESSWORK.</span></h2></div><div className="pdp-tab-content"><div className="pdp-tabs" role="tablist" aria-label="Product information">{['Overview','Before you choose','Visit & enquire'].map((t,i)=><button key={t} role="tab" id={'tab-'+i} aria-controls="product-panel" aria-selected={tab===t} tabIndex={tab===t?0:-1} onClick={()=>setTab(t)} onKeyDown={e=>{const keys=['Overview','Before you choose','Visit & enquire'];let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();setTab(keys[next]);document.getElementById('tab-'+next).focus()}}}>{t}</button>)}</div><div role="tabpanel" id="product-panel" aria-labelledby={'tab-'+['Overview','Before you choose','Visit & enquire'].indexOf(tab)} tabIndex="0">{tab==='Overview'?<><p>{p.description}</p><dl><div><dt>Brand</dt><dd>{p.brand}</dd></div><div><dt>Product type</dt><dd>{p.type}</dd></div><div><dt>Flavours & pack sizes</dt><dd>Confirm with the store</dd></div><div><dt>Price & availability</dt><dd>On enquiry</dd></div></dl></>:tab==='Before you choose'?<><h3>A closer look at the label.</h3><p>Formulas and nutrition information can vary by flavour, pack and market. Ask our team for the current product label, ingredients, allergen information, seal and expiry details before ordering.</p><p>Images show representative packaging. We’ll help you confirm the exact variant available at S&S.</p></>:<><h3>Real people. Right here.</h3><p>Visit S&S Sports & Supplements in Banaswadi, near Amma Pastries and opposite SBI Bank. Talk through the options in person or send your bag as an enquiry.</p><a className="text-link" href="tel:+917022825588">Call +91 70228 25588 ↗</a></>}</div></div></section>
<section className="section pdp-related"><div className="section-heading"><div><div className="section-kicker">KEEP EXPLORING</div><h2>MORE GOOD <span>COMPANY.</span></h2></div><a className="text-link" href="/#shop">Explore the shelf ↗</a></div><div className="product-grid related-grid">{related.map(x=><ProductCard p={x} key={x.id}/>)}</div></section>
<div className={'pdp-mobile-bar '+(showSticky?'shown':'')} inert={!showSticky}><div><strong>{p.name}</strong><span>Enquire for price</span></div><button className="button dark" onClick={add}>Add to bag +</button></div>
<dialog className="zoom-dialog" ref={zoom} onClick={e=>{if(e.target===zoom.current)zoom.current.close()}}><button className="close" aria-label="Close enlarged image" onClick={()=>zoom.current.close()}>×</button><img src={p.image} alt={p.brand+' '+p.name+' enlarged packaging'}/><p>Representative packaging · Confirm the available variant with S&S.</p></dialog></>}

const hero=document.getElementById('hero-react');if(hero)createRoot(hero).render(<Hero/>);
const page=document.getElementById('product-react');if(page){const p=products.find(p=>p.slug===page.dataset.slug);if(p)createRoot(page).render(<ProductPage p={p}/>)}

if(!hero&&!page){const cleanup=initMotion();window.addEventListener("pagehide",cleanup,{once:true})}

const reviewsRoot=document.getElementById('reviews-react');if(reviewsRoot)createRoot(reviewsRoot).render(<Reviews/>);
