import React,{useEffect,useRef,useState} from 'react';
import products from './products.json';
import {initMotion} from './scroll-motion.js';
export default function Hero(){
 const slides=products.filter(p=>p.heroImage);const [ready,setReady]=useState({}),[index,setIndex]=useState(0),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[focused,setFocused]=useState(false),[inView,setInView]=useState(true),[hidden,setHidden]=useState(document.hidden),[reduced,setReduced]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches);const root=useRef(null),touch=useRef(null);const p=slides[index]||products.find(p=>p.id==='mt');const stopped=paused||hover||focused||hidden||reduced||!inView;
 useEffect(()=>{const cleanup=initMotion();const media=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(media.matches),visibility=()=>setHidden(document.hidden);media.addEventListener('change',change);document.addEventListener('visibilitychange',visibility);const io=new IntersectionObserver(([e])=>setInView(e.isIntersecting),{threshold:.1});io.observe(root.current);return()=>{cleanup();io.disconnect();media.removeEventListener('change',change);document.removeEventListener('visibilitychange',visibility)}},[]);
 useEffect(()=>{if(stopped||slides.length<2)return;const t=setInterval(()=>setIndex(i=>ready[slides[(i+1)%slides.length].id]?(i+1)%slides.length:i),6500);return()=>clearInterval(t)},[stopped,index,slides.length,ready]);
 const choose=i=>{setIndex((i+slides.length)%slides.length);setPaused(true)};
 return <div className="campaign" ref={root} role="region" aria-roledescription="carousel" aria-label="Featured protein collection" onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(true)}} onPointerLeave={()=>setHover(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false)}} onTouchStart={e=>touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5)choose(index+(dx<0?1:-1));touch.current=null}}>
 <div className="campaign-grid" aria-hidden="true"/><div className="campaign-top"><span>S&S / THE PERFORMANCE EDIT</span><span>BANASWADI · BENGALURU</span></div>
 <div className="campaign-intro"><span className="edition-tag">GOOD FUEL. BIG GOALS.</span><h1>FUEL YOUR<br/>NEXT LEVEL.</h1><p>Standout brands.<br/>A protein for your routine.<br/>People who know the difference.</p><a className="campaign-text-link" href="/shop/">Explore the collection ↗</a></div>
 <div className="campaign-word" aria-hidden="true">PROTEIN</div>
 <div className="campaign-product">{slides.map((s,i)=><a key={s.id} className={'campaign-pack '+(i===index?'is-current':'')} href={'/products/'+s.slug+'/'} aria-label={'Explore '+s.name} aria-hidden={i!==index} inert={i!==index} tabIndex={i===index?0:-1}><img src={s.heroImage} alt={i===index?s.brand+' '+s.name:''} width="900" height="1000" decoding="async" onLoad={async e=>{const img=e.currentTarget;try{await img.decode()}catch{}setReady(r=>({...r,[s.id]:true}))}} fetchPriority={i===0?'high':'auto'}/></a>)}</div>
 <div className="campaign-card"><div className="campaign-copy" key={p.id}><div className="campaign-brand">{p.brand}</div><h2>{p.name}</h2><span className="campaign-type">{p.type}</span></div><div className="campaign-card-line"/><p>Find your flavour.<br/>Ask us for today’s price.</p><button onClick={()=>window.ssStore.add(p.id)} className="campaign-add">Add to bag <span>+</span></button><a href={'/products/'+p.slug+'/'}>Discover this protein ↗</a></div>
 <div className="campaign-bottom"><div className="campaign-trust"><strong>5.0 <span>★★★★★</span></strong><span>158 Google reviews<br/>Your local nutrition store.</span></div><span className="campaign-footer-copy">FOR EVERY REP. FOR EVERY VERSION OF YOU.</span><div className="campaign-controls"><button onClick={()=>choose(index-1)} aria-label="Previous featured protein">←</button><span aria-live={stopped?'polite':'off'}>{String(index+1).padStart(2,'0')} / {String(slides.length).padStart(2,'0')}</span><button onClick={()=>choose(index+1)} aria-label="Next featured protein">→</button><button disabled={reduced||slides.length<2} onClick={()=>{setPaused(v=>!v);setFocused(false)}} aria-label={paused?'Play product carousel':'Pause product carousel'}>{paused||reduced?'▷':'Ⅱ'}</button></div></div>
 </div>
}
