import {WebGLRenderer,Scene,PerspectiveCamera,Group,TorusGeometry,MeshStandardMaterial,Mesh,AmbientLight,DirectionalLight,Color} from 'three';
export function createOrbit(host,color){
 const renderer=new WebGLRenderer({alpha:true,antialias:false,powerPreference:'low-power'});renderer.setClearColor(0,0);renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer: coarse)').matches?1:1.5));host.appendChild(renderer.domElement);
 const scene=new Scene(),camera=new PerspectiveCamera(35,1,.1,30);camera.position.z=8.5;const group=new Group();scene.add(group);const material=new MeshStandardMaterial({color,metalness:.52,roughness:.34,transparent:true,opacity:.45});const rings=[];for(let i=0;i<3;i++){const geometry=new TorusGeometry(1.75+i*.28,.012+i*.005,8,96);const ring=new Mesh(geometry,material);ring.rotation.set(.5+i*.6,.15+i*.38,i*.5);group.add(ring);rings.push(ring)}scene.add(new AmbientLight(0xffffff,2));const light=new DirectionalLight(0xffffff,3);light.position.set(3,5,6);scene.add(light);
 let visible=false,frame=0,last=0,disposed=false,scrollValue=0;const api={paused:false,setColor(c){material.color=new Color(c)},dispose};const resize=()=>{const {width,height}=host.getBoundingClientRect();if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();render()};const render=()=>{if(!disposed)renderer.render(scene,camera)};
 const animate=t=>{frame=0;if(disposed||!visible||document.hidden)return;if(t-last>32){const elapsed=Math.min((t-last)/1000,.05);last=t;if(!api.paused){group.rotation.z+=elapsed*.055;group.rotation.y=Math.sin(t*.00013)*.2+scrollValue;group.rotation.x=.15+scrollValue*.3}render()}frame=requestAnimationFrame(animate)};
 const restart=()=>{cancelAnimationFrame(frame);frame=0;if(!disposed&&visible&&!document.hidden){last=performance.now();frame=requestAnimationFrame(animate)}};const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;restart()},{threshold:0});io.observe(host);const ro=new ResizeObserver(resize);ro.observe(host);document.addEventListener('visibilitychange',restart);const onScroll=()=>{if(visible)scrollValue=Math.max(-.5,Math.min(.5,host.getBoundingClientRect().top/innerHeight*.35))};window.addEventListener('scroll',onScroll,{passive:true});const lost=e=>{e.preventDefault();dispose()};renderer.domElement.addEventListener('webglcontextlost',lost);resize();
 function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(frame);io.disconnect();ro.disconnect();document.removeEventListener('visibilitychange',restart);window.removeEventListener('scroll',onScroll);renderer.domElement.removeEventListener('webglcontextlost',lost);rings.forEach(r=>r.geometry.dispose());material.dispose();renderer.dispose();renderer.domElement.remove()}
 return api;
}
