export function makePages(home,products,goals){
 const between=(start,end)=>home.slice(home.indexOf(start),home.indexOf(end));
 const shop=between('<section class="shop section"','<section class="about section"');
 const about=between('<section class="about section"','<section class="reviews section"');
 const reviews=between('<section class="reviews section"','<section class="visit section"');
 const visit=home.slice(home.indexOf('<section class="visit section"'),home.indexOf('</main>'));
 const intro=(eyebrow,title,copy,cls='')=>`<section class="page-intro ${cls}"><div class="section-kicker">${eyebrow}</div><h1>${title}</h1><p>${copy}</p></section>`;
 const shopHead=intro('THE S&S COLLECTION','FIND YOUR<br><em>EVERYDAY EDGE.</em>','Explore supplements from familiar names and discover a few new favourites.');
 const brandCards=[...new Set(products.map(p=>p.brand))].map((brand,i)=>{const p=products.find(p=>p.brand===brand);return `<a class="brand-tile" href="/shop/?brand=${encodeURIComponent(brand)}" style="--brand-color:${p.color}"><div class="brand-tile-top"><span>0${i+1} / THE BRAND EDIT</span><span>↗</span></div><h2>${brand}</h2><img src="${p.image}" alt="${brand} ${p.name}" loading="lazy" width="500" height="500"><div class="brand-tile-bottom"><span>${p.type}</span><span>Explore brand</span></div></a>`}).join('');
 const goalSection=between('<!-- GOALS_START -->','<!-- GOALS_END -->').replace('<!-- GOALS_START -->','');
 const goalPages=Object.fromEntries(goals.map(g=>['goals/'+g.slug,{title:g.name,body:intro('SHOP BY ROUTINE',g.name.toUpperCase(),g.copy)+shop}]));
 return {...goalPages,
 shop:{title:'Shop supplements',body:shopHead+goalSection+shop},
 search:{title:'Find your protein',body:intro('THE SEARCH STARTS HERE','YOUR NEXT<br><em>GREAT FIND.</em>','Search by product or brand. Find a familiar favourite or explore something new.','search-intro')+shop.replace('THE SUPPLEMENT SHELF','SEARCH THE COLLECTION')},
 brands:{title:'Our brands',body:intro('MULTIPLE BRANDS. ONE DESTINATION.','GOOD<br><em>COMPANY.</em>','Different approaches to nutrition. One place to explore them.','brands-intro')+`<section class="brand-collection">${brandCards}</section><div class="page-footnote">Brand selection is illustrative. Please confirm current stock with S&S.</div>`},
 'why-ss':{title:'Why S&S',body:intro('THE PEOPLE BEHIND YOUR PROTEIN','LOCAL ROOTS.<br><em>BIGGER GOALS.</em>','Sports nutrition, equipment and an honest conversation. Right here in Banaswadi.','why-intro')+`<section class="why-statement"><span>OUR APPROACH / 01</span><p>The best choice is the one<br>you <em>understand.</em></p><div>We help you compare products, read the label and find an option for your routine. Visit the store for a closer look before you decide.</div></section>`+about+reviews},
 visit:{title:'Visit S&S Banaswadi',body:intro('BANASWADI, BENGALURU','LET’S TALK<br><em>IN PERSON.</em>','Your neighbourhood sports and supplements store. Come for the options. Stay for the conversation.','visit-intro')+visit+`<section class="visit-details"><div><span>01 / FIND US</span><h2>A familiar spot<br>in Banaswadi.</h2><p>7th Main Road, 80 Feet Road, Subbaiahnapalya. Near Amma Pastries and opposite SBI Bank.</p><a href="https://www.google.com/maps/search/?api=1&query=S%26S+Sports+and+Supplements+Banaswadi" target="_blank" rel="noopener">Open Google Maps ↗</a></div><div><span>02 / BEFORE YOU VISIT</span><h2>A quick call.<br>A better visit.</h2><p>Call to check today’s opening hours, product availability, flavours and pack sizes.</p><a href="tel:+917022825588">+91 70228 25588 ↗</a></div></section>`},
 bag:{title:'Your enquiry bag',body:intro('YOUR SELECTION','MAKE IT<br><em>YOUR ROUTINE.</em>','A few good choices, ready for a conversation with our team.','bag-intro')+`<section class="bag-layout"><div><h2>Your bag</h2><div id="bag-page-items"></div></div><aside><div class="section-kicker">THE NEXT STEP</div><h2>Let’s find<br>your fit.</h2><div id="bag-page-bottom"></div><p class="bag-help">No payment is taken here. S&S will confirm availability, flavours, pack sizes and pricing with you.</p><a href="/shop/" class="text-link">Keep exploring ↗</a></aside></section>`}
 };
}
