import React,{useEffect,useRef,useState} from 'react';
const reviews=[{name:'Divya Kotesh',initials:'DK',quote:'Products are original, rates are fair, and service is excellent.'},{name:'Sujeet Ganji',initials:'SG',quote:'A perfect place for athletes, gym lovers, and sports enthusiasts.'}];
const maps='https://www.google.com/maps/search/?api=1&query=S%26S+Sports+and+Supplements+Banaswadi';
export default function Reviews(){
 const [index,setIndex]=useState(0),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[focus,setFocus]=useState(false),[visible,setVisible]=useState(false),[hidden,setHidden]=useState(document.hidden),[reduced,setReduced]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches);const root=useRef(null);const stopped=paused||hover||focus||!visible||hidden||reduced;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(media.matches),visibility=()=>setHidden(document.hidden);media.addEventListener('change',change);document.addEventListener('visibilitychange',visibility);const io=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{threshold:.25});io.observe(root.current);return()=>{io.disconnect();media.removeEventListener('change',change);document.removeEventListener('visibilitychange',visibility)}},[]);
 useEffect(()=>{if(stopped)return;const t=setTimeout(()=>setIndex(i=>(i+1)%reviews.length),8000);return()=>clearTimeout(t)},[stopped,index]);
 const select=i=>{setIndex((i+reviews.length)%reviews.length);setPaused(true)};const current=reviews[index],next=reviews[(index+1)%reviews.length];
 return <div className="review-shell" ref={root} role="region" aria-roledescription="carousel" aria-label="Customer reviews" onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(true)}} onPointerLeave={()=>setHover(false)} onFocusCapture={()=>setFocus(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocus(false)}}>
 <div className="review-top"><div><div className="section-kicker">WHAT THEY SAY ABOUT S&S</div><h2>Good words.<br/><span>From our community.</span></h2><p>A local store. Real conversations.<br/>Here’s what our customers shared.</p></div><a className="review-rating" href={maps} target="_blank" rel="noopener"><strong>5.0 <span aria-label="5 stars">★★★★★</span></strong><span>158 Google reviews ↗</span></a></div>
 <div className="review-stage"><div className="review-identity" aria-hidden="true"><span>S&S / THE LOCAL WORD</span><strong key={current.initials}>{current.initials}</strong><span>YOUR NEIGHBOURHOOD<br/>NUTRITION STORE</span></div><div className="review-feature" aria-live={stopped?'polite':'off'}><div key={current.name} className="review-transition"><span className="quote-mark" aria-hidden="true">“</span><blockquote><p>{current.quote}</p><footer><strong>{current.name}</strong><span>Google review</span></footer></blockquote></div></div><button className="review-next-card" onClick={()=>select(index+1)} aria-label={'Read review by '+next.name}><span className="review-mini-avatar">{next.initials}</span><span>UP NEXT</span><strong>{next.name}</strong><span>Read their words ↗</span></button></div>
 <div className="review-bottom"><a className="button dark" href={maps} target="_blank" rel="noopener">Read reviews on Google <span>↗</span></a><div className="review-controls"><button onClick={()=>select(index-1)} aria-label="Previous customer review">←</button><span>{String(index+1).padStart(2,'0')} / 02</span><button onClick={()=>select(index+1)} aria-label="Next customer review">→</button><button disabled={reduced} onClick={()=>{setPaused(p=>!p);setFocus(false)}} aria-label={paused?'Play customer reviews':'Pause customer reviews'}>{paused||reduced?'▷':'Ⅱ'}</button></div></div></div>
}
